// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const IS_DEV = import.meta.env.DEV;

const requestCounters = new Map<string, number>();

const instrumentedFetch: typeof fetch = async (input, init) => {
  const response = await fetch(input, init);

  if (IS_DEV) {
    const url = typeof input === "string" ? input : input.url;
    if (url.startsWith(SUPABASE_URL)) {
      const endpoint = url.replace(SUPABASE_URL, "").split("?")[0];
      const count = (requestCounters.get(endpoint) ?? 0) + 1;
      requestCounters.set(endpoint, count);
    }
  }

  return response;
};

if (IS_DEV && typeof window !== "undefined") {
  (window as any).__supabaseMetrics = {
    snapshot: () => Object.fromEntries(requestCounters.entries()),
    clear: () => requestCounters.clear(),
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: instrumentedFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});